version: '3.7'
services:
  api:
    image: ddd_edd_practice/api:latest
    build:
      context: .
      dockerfile: deploy/api/docker/Dockerfile
    volumes:
        - ./:/srv/
    ports:
      - "5000:${DDD_EDD_PRACTICE_API_PORT}"
    container_name: ddd_edd_practice-api
    restart: on-failure
    env_file:
      - .env
