version: '3.7'
services:
  api:
    image: ddd_edd_practice/api:latest
    build:
      context: .
      dockerfile: deploy/api/docker/Dockerfile
      args:
        development: "True"
    volumes:
        - ./:/srv/
    ports:
      - "5000:5000"
    container_name: ddd_edd_practice-api
    restart: on-failure
    env_file:
      - .env
