version: "3.7"
services:
  fastapi-vscode-debug-setup:
    image: fastapi-vscode-debug-setup
    build:
      context: .
      dockerfile: deploy/api/debug/Dockerfile
    volumes:
      - ./:/srv/
    command: ["sh",
      "-c",
      "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.ddd_edd_practice_app:app --reload --host 0.0.0.0 --port 5000",
    ]
    environment:
      - APP_MESSAGE=Hello debugger
    ports:
      - 5000:5000
      - 5678:5678
    env_file:
      - .env